In [3]:
import os
import sys
import csv
import numpy as np
from sklearn import svm
from sklearn.metrics import confusion_matrix as cmat
import collections
import itertools
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report as report  
from sklearn.model_selection import *
from sklearn.feature_selection import *
import matplotlib.pyplot as plt
import time
import random
import numpy
from datetime import datetime
import pandas as pd
import requests
import re
import xarray as xr
import pickle

In [4]:
directory ='../data/line_p_data/Rosette'
filename = directory+'/'+'cruise-2007-13-station-ros.csv'
#fieldnames = ['Pressure','Temperature','Salinity','Sigma-t','Oxygen_v','Oxygen_m','Fluorescence']

ross_data = pd.DataFrame()

ross_data = pd.read_csv(filename)
ross_data

,TIME,DATE,LATITUDE,LONGITUDE,CTDPRS,CTDTMP,CTDSAL,OXYGEN,SILCAT,PHSPHT,NO2_NO3
0,09:01,01/06/2007,48.57516,-125.49950,12.5,10.9958,NaN,301.9,NaN,NaN,NaN
1,09:01,01/06/2007,48.57516,-125.49950,12.4,11.0003,NaN,303.1,NaN,NaN,NaN
2,09:01,01/06/2007,48.57516,-125.49950,12.5,10.9999,31.5060,304.0,22.7,1.00,8.9
3,09:01,01/06/2007,48.57516,-125.49950,6.3,10.9973,31.5039,305.0,22.7,0.98,8.9
4,11:45,01/06/2007,48.59967,-126.00100,112.9,6.6316,NaN,76.7,64.6,2.78,33.9
5,11:45,01/06/2007,48.59967,-126.00100,100.2,6.7009,33.9008,73.8,64.2,2.79,33.9
6,11:45,01/06/2007,48.59967,-126.00100,76.1,7.4202,33.3080,124.2,47.4,2.38,29.1
7,11:45,01/06/2007,48.59967,-126.00100,76.3,7.4064,33.3110,125.5,47.5,2.38,29.1
8,11:45,01/06/2007,48.59967,-126.00100,49.8,8.0805,32.5461,156.3,39.5,2.14,26.7
9,11:45,01/06/2007,48.59967,-126.00100,26.0,9.5459,31.6501,274.1,11.8,0.81,5.9
10,11:45,01/06/2007,48.59967,-126.00100,12.0,11.3104,31.3358,327.3,3.3,0.24,0.2
11,11:45,01/06/2007,48.59967,-126.00100,6.1,11.3338,31.3110,330.6,2.8,0.21,0.1
12,16:13,01/06/2007,48.64983,-126.66700,1306.8,2.8326,34.4862,23.4,154.1,3.35,45.4
13,16:13,01/06/2007,48.64983,-126.66700,1250.7,2.9883,34.4659,19.7,148.7,3.37,44.6
14,16:13,01/06/2007,48.64983,-126.66700,1002.4,3.5110,NaN,12.0,134.3,3.39,45.7
15,16:13,01/06/2007,48.64983,-126.66700,1002.4,3.5109,NaN,12.0,133.8,3.40,44.6
16,16:13,01/06/2007,48.64983,-126.66700,1003.4,3.5107,34.3875,12.0,132.6,3.39,43.7
17,16:13,01/06/2007,48.64983,-126.66700,801.1,4.0032,34.3029,10.1,117.1,3.37,44.0
18,16:13,01/06/2007,48.64983,-126.66700,601.5,4.5219,34.1905,17.3,100.1,3.29,43.9
19,16:13,01/06/2007,48.64983,-126.66700,501.2,4.9120,NaN,25.1,88.6,3.19,43.0
20,16:13,01/06/2007,48.64983,-126.66700,501.8,4.9025,NaN,25.1,88.6,3.19,42.7
21,16:13,01/06/2007,48.64983,-126.66700,399.6,5.2329,34.0445,44.6,77.2,3.02,41.3
22,16:13,01/06/2007,48.64983,-126.66700,301.9,5.7320,33.9623,76.8,63.4,2.76,37.1
23,16:13,01/06/2007,48.64983,-126.66700,250.8,5.7851,33.8842,118.4,54.9,2.47,33.8
24,16:13,01/06/2007,48.64983,-126.66700,199.7,6.4756,33.8739,124.6,47.8,2.36,31.5
25,16:13,01/06/2007,48.64983,-126.66700,175.3,6.8217,33.8642,122.8,45.1,2.35,30.7
26,16:13,01/06/2007,48.64983,-126.66700,151.5,7.0871,33.7737,136.7,40.1,2.24,29.7
27,16:13,01/06/2007,48.64983,-126.66700,125.1,7.3719,33.4997,164.8,32.3,2.02,26.1
28,16:13,01/06/2007,48.64983,-126.66700,101.7,7.3110,33.0000,231.9,22.4,1.60,19.1
29,16:13,01/06/2007,48.64983,-126.66700,76.9,7.2535,32.4860,293.0,13.9,1.16,11.3
...,...,...,...,...,...,...,...,...,...,...,...
423,13:47,12/06/2007,50.45067,-145.00150,4.9,6.6914,32.5847,308.3,23.8,1.35,13.7
424,22:27,07/06/2007,50.12800,-144.84666,30.7,6.9896,NaN,311.7,NaN,NaN,NaN
425,22:27,07/06/2007,50.12800,-144.84666,21.7,7.0063,NaN,314.6,NaN,NaN,NaN
426,22:27,07/06/2007,50.12800,-144.84666,11.7,7.0142,NaN,315.7,NaN,NaN,NaN
427,22:27,07/06/2007,50.12800,-144.84666,6.7,7.0220,NaN,316.6,NaN,NaN,NaN
428,22:27,07/06/2007,50.12800,-144.84666,2.1,7.0225,NaN,317.8,NaN,NaN,NaN
429,11:52,10/06/2007,46.99900,-144.66983,4762.9,1.5635,NaN,148.0,179.8,2.67,36.6
430,11:52,10/06/2007,46.99900,-144.66983,4001.8,1.4966,34.6848,142.2,173.1,2.68,36.8
431,11:52,10/06/2007,46.99900,-144.66983,3501.9,1.4973,34.6760,132.4,171.9,2.72,37.5
432,11:52,10/06/2007,46.99900,-144.66983,3001.6,1.5570,34.6603,114.3,173.7,2.81,38.6
433,11:52,10/06/2007,46.99900,-144.66983,2502.7,1.7016,NaN,87.3,176.2,2.94,40.3
434,11:52,10/06/2007,46.99900,-144.66983,2002.4,1.9497,NaN,54.6,175.9,3.09,42.4
435,11:52,10/06/2007,46.99900,-144.66983,1501.1,2.3561,NaN,21.4,168.0,3.24,44.5
436,11:52,10/06/2007,46.99900,-144.66983,1251.3,2.6526,NaN,12.9,159.7,3.28,45.0
437,11:52,10/06/2007,46.99900,-144.66983,1003.8,2.9947,NaN,13.9,146.9,3.26,44.7
438,11:52,10/06/2007,46.99900,-144.66983,802.3,3.3509,NaN,21.9,133.4,3.20,43.9
439,11:52,10/06/2007,46.99900,-144.66983,603.2,3.7093,NaN,27.9,117.3,3.15,43.5
440,11:52,10/06/2007,46.99900,-144.66983,400.6,4.4379,NaN,65.5,88.8,2.85,39.8
441,11:52,10/06/2007,46.99900,-144.66983,302.5,4.7362,NaN,104.9,73.1,2.57,35.8
442,11:52,10/06/2007,46.99900,-144.66983,250.6,5.1217,NaN,145.7,60.4,2.30,31.3
443,11:52,10/06/2007,46.99900,-144.66983,201.1,5.7054,NaN,188.8,47.5,1.96,26.6
444,11:52,10/06/2007,46.99900,-144.66983,175.5,6.0160,NaN,208.4,40.8,1.78,24.2
445,11:52,10/06/2007,46.99900,-144.66983,150.8,6.1187,NaN,233.1,34.1,1.63,21.7
446,11:52,10/06/2007,46.99900,-144.66983,124.8,6.0183,NaN,262.8,26.7,1.51,19.1
447,11:52,10/06/2007,46.99900,-144.66983,99.1,5.9702,NaN,308.7,20.1,1.28,12.9
448,11:52,10/06/2007,46.99900,-144.66983,75.9,6.0336,NaN,311.6,19.5,1.27,12.9
449,11:52,10/06/2007,46.99900,-144.66983,52.4,7.4515,NaN,309.9,18.1,1.20,11.6
450,11:52,10/06/2007,46.99900,-144.66983,27.1,8.0132,NaN,305.9,17.9,1.18,11.4
451,11:52,10/06/2007,46.99900,-144.66983,11.9,8.0141,NaN,307.1,18.0,1.18,11.4
452,11:52,10/06/2007,46.99900,-144.66983,6.7,8.0149,32.5361,307.9,18.1,1.18,11.4

In [8]:
directory = '../data/line_p_data/Rosette'

ross_data = pd.DataFrame()


for filename in os.listdir(directory):
   # print(filename)
    each_data = pd.read_csv(directory+'/'+filename, error_bad_lines=False)
    ross_data = pd.concat([ross_data,each_data],axis=0)

ross_data

,TIME,DATE,LATITUDE,LONGITUDE,CTDPRS,CTDTMP,CTDSAL,OXYGEN,SILCAT,PHSPHT,NO2_NO3
0,10:21,09/02/2007,48.57583,-125.49966,6.0,8.4299,31.9715,281.6,24.70,1.460,16.80
1,12:45,09/02/2007,48.60050,-126.00050,5.8,8.2880,31.8478,280.4,28.60,1.490,17.30
2,14:56,09/02/2007,48.62533,-126.33334,4.6,8.3349,31.5109,287.0,26.60,1.360,15.60
3,16:48,09/02/2007,48.65033,-126.66700,5.2,8.7896,32.3942,286.5,15.50,1.100,11.20
4,18:48,09/02/2007,48.65000,-126.66650,7.8,8.7918,NaN,288.6,14.90,1.100,11.40
5,18:48,09/02/2007,48.65000,-126.66650,7.7,8.7917,32.4082,288.6,15.10,1.100,11.40
6,18:48,09/02/2007,48.65000,-126.66650,2.2,8.7938,NaN,288.6,14.90,1.090,11.40
7,23:00,09/02/2007,48.69100,-127.16534,4.9,8.4059,32.4182,290.8,9.80,1.000,8.60
8,02:35,10/02/2007,48.74367,-127.66666,7.2,8.3560,32.4127,291.6,8.50,0.950,8.00
9,06:24,10/02/2007,48.77717,-128.17084,2.3,8.2108,32.4009,293.0,10.30,1.040,9.50
10,10:12,10/02/2007,48.81650,-128.66684,3.4,8.1030,32.4147,295.3,7.70,0.940,7.90
11,13:45,10/02/2007,48.85667,-129.16617,5.2,7.9226,32.4237,292.6,7.40,0.970,8.30
12,16:39,10/02/2007,48.89317,-129.66550,5.1,8.2017,32.4476,291.8,6.40,0.890,7.20
13,20:07,10/02/2007,48.93333,-130.16701,6.0,8.2174,32.4480,293.3,6.40,0.900,7.20
14,23:23,10/02/2007,48.97050,-130.66667,4.6,8.4041,NaN,294.8,6.50,0.890,6.60
15,23:23,10/02/2007,48.97050,-130.66667,3.1,8.4056,NaN,294.9,6.70,0.880,6.80
16,02:34,11/02/2007,48.97066,-130.66701,5.6,8.4060,32.4450,293.1,6.50,0.880,6.90
17,02:34,11/02/2007,48.97066,-130.66701,5.6,8.4056,32.4446,292.9,6.70,0.880,6.70
18,08:27,11/02/2007,49.04300,-131.66716,4.4,8.3567,32.4426,290.3,6.20,0.900,6.90
19,13:17,11/02/2007,49.12383,-132.66716,3.3,7.6404,32.4877,295.2,9.70,1.080,9.70
20,18:10,11/02/2007,49.20050,-133.66583,6.0,7.1608,32.3856,299.4,12.20,1.140,10.90
21,23:52,11/02/2007,49.28316,-134.66650,5.3,7.0838,NaN,306.0,11.70,1.160,11.30
22,23:52,11/02/2007,49.28316,-134.66650,5.4,7.0865,32.4050,305.9,12.20,1.160,11.10
23,23:52,11/02/2007,49.28316,-134.66650,1.3,7.0954,NaN,305.7,12.20,1.150,11.10
24,02:27,12/02/2007,49.28300,-134.66634,6.0,7.0891,32.3998,303.9,12.50,1.150,10.90
25,09:08,12/02/2007,49.35000,-135.66750,6.9,7.0958,32.4656,298.0,11.60,1.140,10.70
26,14:10,12/02/2007,49.43350,-136.66667,4.4,7.1859,32.4903,297.0,11.90,1.150,10.90
27,19:28,12/02/2007,49.50000,-137.66650,5.1,6.9253,32.4881,300.0,11.60,1.160,10.90
28,00:40,13/02/2007,49.56867,-138.66733,5.9,6.7315,NaN,305.9,13.00,1.190,11.40
29,00:40,13/02/2007,49.56867,-138.66733,6.2,6.7321,32.5129,305.9,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
473,22:03,26-02-18,50.00050,-144.99966,5.4,5.8913,NaN,311.6,NaN,NaN,NaN
474,22:03,26-02-18,50.00050,-144.99966,5.5,5.8922,NaN,312.1,NaN,NaN,NaN
475,22:03,26-02-18,50.00050,-144.99966,5.5,5.9306,NaN,312.1,21.45,1.317,14.71
476,00:08,27-02-18,49.99933,-144.99950,2001.5,1.9615,NaN,51.6,NaN,NaN,NaN
477,00:08,27-02-18,49.99933,-144.99950,2001.6,1.9613,NaN,51.5,NaN,NaN,NaN
478,00:08,27-02-18,49.99933,-144.99950,2001.1,1.9614,NaN,51.6,NaN,NaN,NaN
479,00:08,27-02-18,49.99933,-144.99950,2001.3,1.9612,NaN,51.6,NaN,NaN,NaN
480,00:08,27-02-18,49.99933,-144.99950,1000.2,2.9628,NaN,18.6,NaN,NaN,NaN
481,00:08,27-02-18,49.99933,-144.99950,1001.4,2.9624,NaN,18.6,NaN,NaN,NaN
482,00:08,27-02-18,49.99933,-144.99950,1000.7,2.9628,NaN,18.6,NaN,NaN,NaN
483,00:08,27-02-18,49.99933,-144.99950,1000.8,2.9628,NaN,18.6,NaN,NaN,NaN
484,00:08,27-02-18,49.99933,-144.99950,500.8,3.8487,NaN,37.5,NaN,NaN,NaN
485,00:08,27-02-18,49.99933,-144.99950,501.0,3.8471,NaN,37.4,NaN,NaN,NaN
486,00:08,27-02-18,49.99933,-144.99950,500.6,3.8460,NaN,37.4,NaN,NaN,NaN
487,00:08,27-02-18,49.99933,-144.99950,501.1,3.8440,NaN,37.2,NaN,NaN,NaN
488,00:08,27-02-18,49.99933,-144.99950,300.9,4.0226,NaN,73.6,NaN,NaN,NaN
489,00:08,27-02-18,49.99933,-144.99950,98.5,5.8573,NaN,306.0,NaN,NaN,NaN
490,00:08,27-02-18,49.99933,-144.99950,50.3,5.8905,NaN,310.1,NaN,NaN,NaN
491,00:08,27-02-18,49.99933,-144.99950,24.8,5.8992,NaN,311.6,NaN,NaN,NaN
492,00:08,27-02-18,49.99933,-144.99950,10.0,5.8988,NaN,311.7,NaN,NaN,NaN
493,00:08,27-02-18,49.99933,-144.99950,9.9,5.8988,NaN,312.0,NaN,NaN,NaN
494,00:08,27-02-18,49.99933,-144.99950,10.1,5.8989,NaN,311.5,NaN,NaN,NaN
495,00:08,27-02-18,49.99933,-144.99950,9.9,5.8989,NaN,311.7,NaN,NaN,NaN
496,00:08,27-02-18,49.99933,-144.99950,10.0,5.8992,NaN,311.8,NaN,NaN,NaN
497,00:08,27-02-18,49.99933,-144.99950,5.7,5.9030,NaN,311.9,NaN,NaN,NaN
498,05:27,27-02-18,49.99900,-144.30350,4.9,6.0100,NaN,NaN,NaN,NaN,NaN
499,05:27,27-02-18,49.99900,-144.30350,5.3,6.0104,32.4744,NaN,18.76,1.212,13.67
500,02:45,27-02-18,50.14233,-144.83234,10.3,5.8780,32.4936,313.1,NaN,NaN,NaN
501,02:45,27-02-18,50.14233,-144.83234,7.4,5.8914,32.4955,313.5,NaN,NaN,NaN
502,02:45,27-02-18,50.14233,-144.83234,4.7,5.8798,32.4927,313.8,NaN,NaN,NaN

In [9]:
ross_data = ross_data.fillna(-999.0)
ross_data.astype(bool).sum(axis=0)

TIME         17578
DATE         17578
LATITUDE     17578
LONGITUDE    17578
CTDPRS       17578
CTDTMP       17578
CTDSAL       17578
OXYGEN       17578
SILCAT       17578
PHSPHT       17578
NO2_NO3      17307
dtype: int64

In [10]:
ross_data.to_csv(directory+'/'+'papa_data_consolidated.csv',index=False)

In [ ]:
ross_data = ross_data.replace(-999,np.nan)
ross_data = ross_data.replace('-999.0',np.nan,regex=True)
ross_data = ross_data.replace('-999.00',np.nan)
ross_data = ross_data.replace('-999.0000',np.nan)

In [ ]:
ross_data

In [ ]:
 ross_data.count()